name: Do something (new)

on:
  workflow_dispatch:
    inputs:
      args:
        description: 'An argument'
        required: true
        default: ''

      # Inputs provided by the bot
      distinct_id:
        description: '(bot) A distinct ID'
        required: false
        default: ''
      source_issue:
        description: '(bot) The issue that triggered this workflow'
        required: false
        default: ''
      requesting_user:
        description: '(bot) The user who requested this workflow'
        required: false
        default: ''
      status_comment:
        description: '(bot) The comment to update with the status of this workflow'
        required: false
        default: ''

run-name: ${{ github.workflow }}${{ inputs.distinct_id && format(' (bot run {0})', inputs.distinct_id) || '' }}

permissions:
  contents: read
  issues: write
  pull-requests: write

# Ensure scripts are run with pipefail. See:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sleep $(( 1 + RANDOM % 4 ))

      - run: |
          echo "Running with args: ${{ inputs.args }}"

      - run: exit 1
        if: ${{ inputs.args == 'fail' }}

      - uses: jakebailey/workflow-trigger-testing/.github/actions/post-workflow-result@main
        if: ${{ !cancelled() && inputs.distinct_id }}
        with:
          success_comment: "It worked!."
          failure_comment: 'It failed...'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          distinct_id: ${{ inputs.distinct_id }}
          source_issue: ${{ inputs.source_issue }}
          requesting_user: ${{ inputs.requesting_user }}
          status_comment: ${{ inputs.status_comment }}
